<script>
	import '../../app.css';
	import Navbar from '../Navbar.svelte';
	import Footer from '../Footer.svelte';
</script>

<Navbar />

<div class="pt-12">
	<div class="mx-auto max-w-7xl px-6 lg:px-8">
		<div class="mx-auto max-w-2xl ">
			<img
				class="mx-auto h-12 w-auto"
				src="https://img.icons8.com/color/96/000000/controller.png"
				alt="Your Company"
			/>
			<p class=" text-center mt-2 text-3xl font-mono tracking-tight text-gray-300 sm:text-4xl">
				Privacy <a class="text-amber-500">policy</a>
			</p>
			<p class="mt-6 text-lg leading-8 text-gray-600">
				This Privacy Policy describes Our policies and procedures on the collection, use and
				disclosure of Your information when You use the Service and tells You about Your privacy
				rights and how the law protects You. We use Your Personal data to provide and improve the
				Service. By using the Service, You agree to the collection and use of information in
				accordance with this Privacy Policy.
				<strong>Personal Data</strong> is any information that relates to an identified or
				identifiable individual.
				<strong>Service</strong> refers to the Website.
				<strong>Usage Data</strong> refers to data collected automatically, either generated by the
				use of the Service or from the Service infrastructure itself (for example, the duration of a
				page visit).
				<strong>Website</strong> refers to zadus-gameprice-engine, accessible from
				<a
					href="https://zadus-gameprice-engine.vercel.app/"
					rel="external nofollow noopener"
					target="_blank">https://zadus-gameprice-engine.vercel.app/</a
				>
				<strong>You</strong> means the individual accessing or using the Service, or the company, or
				other legal entity on behalf of which such individual is accessing or using the Service, as
				applicable. While using Our Service, We may ask You to provide Us with certain personally
				identifiable information that can be used to contact or identify You. Personally
				identifiable information may include, but is not limited to: Email address. We may use
				Personal Data for the following purposes:
				<strong>To provide and maintain our Service</strong>, including to monitor the usage of our
				Service.
				<strong>To manage Your Account:</strong> to manage Your registration as a user of the
				Service. The Personal Data You provide can give You access to different functionalities of
				the Service that are available to You as a registered user.
				<strong>To contact You:</strong> To contact You by email.
				<strong>To manage Your requests:</strong> To attend and manage Your requests to Us.
				<strong>For other purposes</strong>: We may use Your information for other purposes, such as
				data analysis, identifying usage trends, determining the effectiveness of our promotional
				campaigns and to evaluate and improve our Service, products, services, marketing and your
				experience. You have the right to delete or request that We assist in deleting the Personal
				Data that We have collected about You. If you have any questions about this Privacy Policy,
				You can contact us. By visiting this page on our website:
				<a
					href="https://zadus-gameprice-engine.vercel.app/contact"
					rel="external nofollow noopener"
					target="_blank">https://zadus-gameprice-engine.vercel.app/contact</a
				>
			</p>
		</div>
	</div>
</div>

<Footer />
